Eight-Corner/CampFire

- workspace/campfire/src/test/test2/onlytest.xml
> 05/28 테스트 용도

- workspace/campfire/src/main/webapp/WEB-INF/views/includes/header.jsp
- workspace/campfire/src/main/webapp/resources/assets/css/layout.css
반응형 범위 수정
@media screen and (max-width: 408px) {
label {
margin: 0;
}
input[type="text"], input[type="password"], input[type="email"] {
height: 3rem;
}
.btn-right {
font-size: 14px;
}
}
> 375 -> 408 반응형범위 수정

- workspace/campfire/src/main/webapp/WEB-INF/views/home.jsp
테스트겸 메인 검색창 반응형수정
home.jsp style
> 테스트겸 메인 검색창 반응형수정

- workspace/campfire/src/main/webapp/WEB-INF/views/home.jsp
735px 이하 원형, 너비 수정
home.jsp style
> 반응형 검색 부분 인풋, 검색 버튼

- workspace/campfire/src/main/webapp/WEB-INF/views/home.jsp
> 모닥불 메세지 반응형 적용 수정

- workspace/campfire/src/main/webapp/resources/assets/css/layout.css
.modal
기본 top: 40% -> 30%로 수정
@media screen and (max-width:1680px)에서
top 40% 추가
> 회원가입 modal top 조정

- workspace/campfire/src/main/webapp/WEB-INF/views/campfire/review.jsp
<div class="imgDiv">
<style>
.imgDiv {
width: 100%;
height: 340px;
margin: 0 auto;
}
.reviewImg {
width: 100%;
height: 100%;
object-fit: cover; 
}
@media screen and (max-width: 980px){
.imgDiv {
width: 80%;
height: 300px; 
}
.info {
width: 80%;
margin: 0 auto;
}
.main-banner-container {
margin-bottom: 5%;
}
}
</style> 추가
> 리뷰게시판 사진 크기 조정 후 object-fit: cover

- workspace/campfire/src/main/webapp/WEB-INF/views/campfire/review.jsp
- workspace/campfire/src/main/webapp/resources/assets/bootstrap-css/bootstrap.min.css
- workspace/campfire/src/main/webapp/resources/assets/css/layout.css
review List header & 버튼 글 정렬 css 스타일 수정
> review List header & 버튼 글 정렬 css 스타일 수정

- workspace/campfire/src/main/java/com/campfire/controller/UserController.java
- workspace/campfire/src/main/java/com/campfire/service/UserService.java
- workspace/campfire/src/main/java/com/campfire/service/UserServiceImpl.java
- workspace/campfire/src/main/webapp/WEB-INF/views/includes/modal.jsp
- workspace/campfire/src/main/webapp/resources/assets/js/user.js
> signIn done

- workspace/campfire/src/main/java/com/campfire/controller/UserController.java
> signUp 완료 시 페이지 이동

- workspace/campfire/src/main/java/com/campfire/controller/UserController.java
- workspace/campfire/src/main/webapp/resources/assets/js/modal.js
- workspace/campfire/src/main/webapp/resources/assets/js/user.js
> UserController url 수정

- workspace/campfire/src/main/webapp/WEB-INF/views/campfire/review.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/elements.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/error_page.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/generic.jsp
> page Title & icon

- workspace/campfire/src/main/webapp/WEB-INF/views/includes/footer.jsp
> footer 반응형 수정

- workspace/campfire/src/main/java/com/campfire/controller/CampfireController.java
- workspace/campfire/src/main/webapp/WEB-INF/views/campfire/freeBoard.jsp
> 자유게시판 리스트(미완) 페이지 추가

- workspace/campfire/src/main/java/com/campfire/mapper/ReviewBoardMapper.java
- workspace/campfire/src/main/resources/META-INF/com/campfire/mapper/ReviewBoardMapper.xml
> ReviewBoardMapper

- workspace/campfire/src/main/java/com/campfire/domain/AllFileDTO.java
- workspace/campfire/src/main/java/com/campfire/domain/PageDTO.java
- workspace/campfire/src/main/resources/META-INF/com/campfire/mapper/FreeBoardMapper.xml
- workspace/campfire/src/test/java/com/campfire/mapper/BoardMapperTests.java
> FreeBoardMapper 테스트까지 완료

- workspace/campfire/src/main/java/com/campfire/domain/freeBoard/FreeBoardAttachVO.java
- workspace/campfire/src/main/java/com/campfire/domain/freeBoard/FreeBoardVO.java
- workspace/campfire/src/main/java/com/campfire/mapper/FreeBoardMapper.java
- workspace/campfire/src/main/java/com/campfire/service/FreeBoardService.java
- workspace/campfire/src/main/java/com/campfire/service/FreeBoardServiceImple.java
- workspace/campfire/src/test/java/com/campfire/service/BoardServiceTests.java
> FreeBoardService

- workspace/campfire/src/main/java/com/campfire/domain/Criteria.java
- workspace/campfire/src/main/java/com/campfire/mapper/FreeBoardAttachMapper.java
- workspace/campfire/src/main/java/com/campfire/mapper/FreeBoardReplyMapper.java
- workspace/campfire/src/main/java/com/campfire/service/FreeBoardReplyService.java
- workspace/campfire/src/main/java/com/campfire/service/FreeBoardReplyServiceImple.java
- workspace/campfire/src/main/java/com/campfire/service/FreeBoardServiceImple.java
- workspace/campfire/src/main/resources/META-INF/com/campfire/mapper/FreeBoardAttachMapper.xml
- workspace/campfire/src/main/resources/META-INF/com/campfire/mapper/FreeBoardReplyMapper.xml
- workspace/campfire/src/test/java/com/campfire/mapper/AttachMapperTests.java
- workspace/campfire/src/test/java/com/campfire/mapper/ReplyMapperTests.java
- workspace/campfire/src/test/java/com/campfire/service/ReplyServiceTests.java
> FreeBoard reply, attach 서비스까지 테스트 종료

- workspace/campfire/src/main/java/com/campfire/domain/PageDTO.java
- workspace/campfire/src/main/java/com/campfire/service/FreeBoardReplyServiceImple.java
PageDTO에 생성자 추가(오버로딩 오류나서 매개변수 순서 변경)
FreeBoardReplyService 코드 추가
> PageDTO, Service 수정

- workspace/campfire/src/main/java/com/campfire/controller/FreeBoardReplyController.java
- workspace/campfire/src/main/java/com/campfire/controller/FreeController.java
- workspace/campfire/src/main/java/com/campfire/controller/UploadController.java
- workspace/campfire/src/main/java/com/campfire/domain/AllFileDTO.java
> freeBoard Controller

- workspace/campfire/src/main/java/com/campfire/controller/UploadController.java
- workspace/campfire/src/main/webapp/WEB-INF/views/free/freeList.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/free/freeWrite.jsp
- workspace/campfire/src/main/webapp/WEB-INF/web.xml
- workspace/campfire/src/test/java/com/campfire/mapper/ReviewMapperTests.java
> 자유게시판 첨부파일 폴더에 업로드까지 성공

- workspace/campfire/src/main/java/com/campfire/controller/HomeController.java
- workspace/campfire/src/main/webapp/WEB-INF/views/free/freeList.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/home.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/includes/header.jsp
> localhost:80

- workspace/campfire/src/main/webapp/WEB-INF/views/free/freeList.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/free/freeView.jsp
- workspace/campfire/src/main/webapp/resources/assets/js/reply.js
add > pull > commit > push 했습니다.
> 댓글 구현중 중간 커밋

- workspace/campfire/src/main/java/com/campfire/controller/FreeBoardReplyController.java
- workspace/campfire/src/main/webapp/WEB-INF/views/free/freeView.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/free/freeWrite.jsp
- workspace/campfire/src/main/webapp/resources/assets/js/reply.js
자유게시판 게시글 등록,
자유게시판 댓글 등록, 수정, 삭제, 목록까지 완료
페이징처리 나오긴 하지만 이동은 안되는 상태
> 댓글 구현 97% 완료

- workspace/campfire/src/main/webapp/WEB-INF/views/includes/header.jsp
홈에서 테스트하고 완성한 건 그대로 잘 되지만, 안 될 수도 있음.
헤더 쪽 필요한 부분도 수정했으나, 로그인 성공은 잘 되지만, 실패 시 오류가 뜸
> 로그인 버그 발견 (로그인 실패 시 NullPointerException)

- workspace/campfire/src/main/java/com/campfire/service/KakaoAPI.java
- workspace/campfire/src/main/webapp/resources/assets/js/user.js
> 일반 로그인시 리다이렉트 추가

- workspace/campfire/src/main/java/com/campfire/controller/FreeBoardReplyController.java
- workspace/campfire/src/main/java/com/campfire/service/UserServiceImpl.java
- workspace/campfire/src/main/webapp/WEB-INF/views/free/freeView.jsp
댓글 페이징 처리 수정,
<a> text-decoration: none으로 수정,
<code> background: white로 수정
> freeView 수정

- workspace/campfire/src/main/java/com/campfire/controller/FreeController.java
- workspace/campfire/src/main/java/com/campfire/domain/freeBoard/FreeBoardVO.java
- workspace/campfire/src/main/java/com/campfire/mapper/FreeBoardMapper.java
- workspace/campfire/src/main/java/com/campfire/service/FreeBoardServiceImple.java
- workspace/campfire/src/main/resources/META-INF/com/campfire/mapper/FreeBoardMapper.xml
- workspace/campfire/src/main/webapp/WEB-INF/views/free/freeList.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/free/freeView.jsp
- workspace/campfire/src/test/java/com/campfire/mapper/BoardMapperTests.java
자유게시판 목록 조회수, 
작성하면 new 아이콘 보여주고, 하루 지나면 사라지는 기능 추가,
자유게시판 상세보기 조회수 추가
> new 수정, 조회수 추가

- workspace/campfire/src/main/webapp/WEB-INF/views/free/freeList.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/free/freeView.jsp
- workspace/campfire/src/main/webapp/resources/assets/css/layout.css
- workspace/campfire/src/main/webapp/resources/assets/css/main.css
main.css 색상 #404040 수정
자유게시판 자잘한 수정
> 전체 색상 변경, 자유게시판 자잘자잘 수정

- workspace/.recommenders/caches/identified-project-coordinates.json
- workspace/campfire/src/main/java/com/campfire/controller/MarketController.java
- workspace/campfire/src/main/java/com/campfire/domain/PageDTO.java
- workspace/campfire/src/main/java/com/campfire/service/MarketReplyService.java
- workspace/campfire/src/main/java/com/campfire/service/MarketReplyServiceImple.java
- workspace/campfire/src/main/webapp/WEB-INF/views/market/marketList.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/market/marketWrite.jsp
- workspace/campfire/src/main/webapp/resources/assets/css/market.css
- workspace/campfire/src/main/webapp/resources/assets/market/vendor/bootstrap/css/bootstrap.min.css
> dropdown 해결, 글쓰기 키워드 추가

- workspace/campfire/src/main/webapp/WEB-INF/views/free/freeList.jsp
> 자유게시판 오류 수정

- workspace/campfire/src/main/java/com/campfire/controller/FreeController.java
- workspace/campfire/src/main/java/com/campfire/controller/MarketController.java
- workspace/campfire/src/main/java/com/campfire/controller/UploadController.java
- workspace/campfire/src/main/webapp/WEB-INF/views/market/marketList.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/market/marketWrite.jsp
- workspace/campfire/src/main/webapp/WEB-INF/web.xml
> 장터게시판 게시글작성까지 완료

- workspace/campfire/src/main/java/com/campfire/controller/FreeController.java
- workspace/campfire/src/main/java/com/campfire/controller/MarketController.java
- workspace/campfire/src/main/java/com/campfire/controller/UploadController.java
- workspace/campfire/src/main/webapp/WEB-INF/views/market/marketList.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/market/marketWrite.jsp
- workspace/campfire/src/main/webapp/WEB-INF/web.xml
Reverts Eight-Corner/CampFire#127
> Revert "장터게시판 게시글작성까지 완료"

- workspace/campfire/src/main/java/com/campfire/controller/MarketController.java
- workspace/campfire/src/main/java/com/campfire/controller/UploadController.java
- workspace/campfire/src/main/webapp/WEB-INF/views/market/marketList.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/market/marketWrite.jsp
- workspace/campfire/src/main/webapp/WEB-INF/web.xml
> 장터게시판 작성하기 완료

- workspace/campfire/src/main/java/com/campfire/controller/MarketController.java
- workspace/campfire/src/main/webapp/WEB-INF/views/market/marketList.jsp
카테고리 변경 시 ajax로 목록 다시 불러오기까지 완성
썸네일 시작해야함
> 장터게시판 ajax

- workspace/campfire/src/main/java/com/campfire/controller/MarketController.java
- workspace/campfire/src/main/java/com/campfire/controller/UploadController.java
- workspace/campfire/src/main/java/com/campfire/domain/marketBoard/MarketBoardVO.java
- workspace/campfire/src/main/java/com/campfire/service/MarketBoardServiceImple.java
- workspace/campfire/src/main/resources/META-INF/com/campfire/mapper/MarketBoardMapper.xml
- workspace/campfire/src/main/webapp/WEB-INF/views/market/marketList.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/market/marketView.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/market/marketWrite.jsp
- workspace/campfire/src/test/java/com/campfire/mapper/MarketMapperTests.java
장터게시판
상세보기 페이지 이미지 100% 고정
글 작성 시 가격 입력 input태그 추가
장터게시판 썸네일
첨부한 이미지 파일 중 첫번째 사진을 MarketBoardVO의 thumbnail 필드에 넣어주는 것
TBL_MARKET_BOARD에 ALTER TABLE TBL_MARKET_BOARD ADD THUMBNAIL VARCHAR2(3000); 추가
작성하기 유효성 검사, 무료나눔 작성 시 금액 입력 input태그 display: none;
카테고리 별 작성하기 진입 시 해당 option으로 selected 등 진행 예정
> 장터게시판 List, View, Write 구현중

- workspace/campfire/src/main/java/com/campfire/controller/MarketController.java
- workspace/campfire/src/main/webapp/WEB-INF/views/market/marketList.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/market/marketView.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/market/marketWrite.jsp
작성하기 유효성 검사(o)
무료나눔 작성 시 금액 입력 input태그에 0 넣고 hide, 
카테고리 별 작성하기 진입 시 해당 option으로 selected(o)
썸네일 사이즈 조정(o)
> 장터게시판 세부조정

- workspace/campfire/src/main/java/com/campfire/controller/MarketController.java
- workspace/campfire/src/main/java/com/campfire/mapper/MarketBoardMapper.java
- workspace/campfire/src/main/java/com/campfire/service/MarketBoardService.java
- workspace/campfire/src/main/java/com/campfire/service/MarketBoardServiceImple.java
- workspace/campfire/src/main/resources/META-INF/com/campfire/mapper/MarketBoardMapper.xml
- workspace/campfire/src/main/webapp/WEB-INF/views/market/marketList.jsp
- workspace/campfire/src/test/java/com/campfire/mapper/MarketMapperTests.java
제목, 내용으로 검색 가능
검색 결과는 카테고리별로 출력
검색 결과가 없을 시 검색 결과가 없습니다라는 문구 출력
> 장터게시판 검색기능 구현

- workspace/campfire/src/main/java/com/campfire/controller/MarketController.java
- workspace/campfire/src/main/java/com/campfire/controller/UploadController.java
- workspace/campfire/src/main/java/com/campfire/service/MarketBoardServiceImple.java
- workspace/campfire/src/main/webapp/WEB-INF/views/free/freeView.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/market/marketView.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/market/marketWrite.jsp
- workspace/campfire/src/main/webapp/WEB-INF/web.xml
> 장터게시판 삭제 진입 전

- workspace/campfire/src/main/java/com/campfire/controller/FreeController.java
- workspace/campfire/src/main/java/com/campfire/controller/MarketController.java
- workspace/campfire/src/main/webapp/WEB-INF/views/free/freeList.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/free/freeModify.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/free/freeWrite.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/market/marketList.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/market/marketModify.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/market/marketView.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/market/marketWrite.jsp
- workspace/campfire/src/main/webapp/WEB-INF/web.xml
장터게시판 수정
첨부파일이 하나도 없는 글에 첨부파일을 추가할 경우
첫번째 사진이 썸네일로 들어감
만약 첨부파일이 있는 글에 첨부파일을 추가할 경우
기존에 있던 썸네일이 유지
첨부파일이 있는 글에서 첨부파일 전체를 삭제할 경우 썸네일 소멸
장터게시판 목록페이지
제목이 길어지면 overflow 적용
장터게시판 작성페이지
금액은 99,999,999 까지 입력 가능
장터게시판 상세페이지
댓글 아이콘, 입력창 길이 수정
작성 후 뒤로가기를 눌렀을 때 alert이 또 나오는 문제
alert 제거
> 장터게시판 첨부파일 및 세부수정

- workspace/campfire/src/main/java/com/campfire/task/FileCheckTask.java
- workspace/campfire/src/main/webapp/WEB-INF/views/campfire/guideModify.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/campfire/guideWrite.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/campfire/tipModify.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/campfire/tipWrite.jsp
> 캠핑 팁, 가이드 첨부 파일 문제 완성 적용

- workspace/campfire/src/main/java/com/campfire/controller/MarketController.java
- workspace/campfire/src/main/java/com/campfire/service/MarketBoardServiceImple.java
- workspace/campfire/src/main/webapp/WEB-INF/views/free/freeModify.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/free/freeView.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/free/freeWrite.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/market/marketModify.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/market/marketView.jsp
- workspace/campfire/src/main/webapp/WEB-INF/web.xml
장터, 자유게시판 댓글 작성 시 댓글 입력칸 비우기(o)
수정하기에서 처음 들어왔을 때 첨부파일 목록을 가져와서
input태그를 만들어두는데
기존에 있던 첨부파일을 삭제했을 경우
input태그는 남아있어서 오류 발생
아무것도 안하고 수정 눌렀을 떄 썸네일 날아감
기존꺼에 하나 추가했을 경우 새로 추가한걸로 썸네일이 교체되는 문제 진행중
> 장터게시판 중간 커밋

- workspace/campfire/src/main/webapp/WEB-INF/views/free/freeList.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/free/freeModify.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/free/freeView.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/free/freeWrite.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/market/marketList.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/market/marketModify.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/market/marketView.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/market/marketWrite.jsp
- workspace/campfire/src/main/webapp/WEB-INF/web.xml
목록, 상세, 작성페이지 320(아이폰 미니) 반응형 수정
> 자유, 장터게시판 320 반응형

- workspace/campfire/src/main/webapp/WEB-INF/views/campfire/guideList.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/campfire/guideModify.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/campfire/guideView.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/campfire/guideWrite.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/campfire/tipList.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/campfire/tipModify.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/campfire/tipView.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/campfire/tipWrite.jsp
- workspace/campfire/src/main/webapp/WEB-INF/views/free/freeList.jsp
> 팁, 가이드 게시판 반응형 수정
